import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Navbar } from "@/components/ui/Navbar";
import Breadcrumb from "@/components/ui/Breadcrumb";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {/* Navbar remains at the top */}
        <Navbar />

        {/* Sticky Breadcrumb that replaces Navbar on scroll */}
        <div className="sticky top-0 left-0 right-0 z-50">
          <Breadcrumb />
        </div>

        {/* Main content should touch the Navbar */}
        <main className="relative mt-0">{children}</main>
      </body>
    </html>
  );
}
